openapi: '3.0.0'
info:
  version: '1.0.0'
  title: LitVar API
  description: >-
    LitVar allows the search and retrieval of variant relevant information from the biomedical literature and shows key biological relations between a variant and its close related entities (e.g. genes, diseases, and drugs). The LitVar results are automatically extracted (with regular updates) from over 27 million PubMed articles as well as applicable full-text articles in PubMed Central.
  termsOfService: https://www.ncbi.nlm.nih.gov/home/about/policies/
  contact:
    name: Zhiyong Lu
    x-role: PI
    email: luzh@ncbi.nlm.nih.gov
servers:
  - url: 'https://www.ncbi.nlm.nih.gov/research/bionlp/litvar/api/v1'
    description: 'Production server'
tags:
  - name: variant
  - name: publication
paths:
  '/public/rsids2pmids':
    get:
      summary: 'Retrieve PMIDs of publications mentioning submitted variants'
      parameters:
        - name: rsids
          in: query
          description: >-
            rsid
          required: true
          x-valueType:
            - 'http://identifiers.org/dbsnp/'
          schema:
            type: string
      responses:
        '200':
          description: 'publications mentioned the submitted variant'
          x-responseValueType:
            - path: data.pmids
              valueType: 'http://identifiers.org/pubmed/'
          x-JSONLDContext:
            'litvar/jsonld_context/rsid2pmid_context.json'
